trigger:
- develop

pool:
  name: 'Default'

variables:
- group: application-var-group
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'Any CPU'
- name: system.debug
  value: true

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    workingDirectory: $(PROJECT_PATH)
  displayName: '[ dotnetTask ] Run dotnet restore'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    workingDirectory: $(PROJECT_PATH)
    arguments: '--configuration $(buildConfiguration)' 
  displayName: '[ dotnetTask ] Build application'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*tests/*.csproj'
    workingDirectory: $(PROJECT_PATH)
    arguments: '--configuration $(buildConfiguration)'
  displayName: '[ dotnetTask ] Test application'
  
- task: Docker@2
  inputs:
    containerRegistry: 'dockerHubConnection'
    repository: 'dotnet-mvc-app-repo'
    command: 'buildAndPush'
    Dockerfile: '$(PROJECT_PATH)/Dockerfile'
  displayName: '[ dockerTask ] docker build and push'
    
